version: '2'
services:
  web:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile-nginx
    ports:
      - "8080:80"
    links:
      - php
      - db
    volumes:
      - .:/usr/share/nginx/html/attendize

  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile-php
    links:
      - db
      - maildev
      - redis
    volumes:
      - .:/usr/share/nginx/html/attendize

  php-worker:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile-php
    links:
      - db
      - maildev
      - redis
    volumes:
      - .:/usr/share/nginx/html/attendize
    command: php artisan queue:work --daemon

  db:
    image: mysql/mysql-server:latest
    environment:
       MYSQL_DATABASE: attendize
       MYSQL_USER: attendize
       MYSQL_PASSWORD: attendize
       MYSQL_ROOT_PASSWORD: attendize
    ports:
      - "3333:3306"
    volumes:
        - ./docker/data/mysql:/var/lib/mysql

  maildev:
    image: djfarrelly/maildev
    ports:
      - "1080:80"
  redis:
    build:
      context: .
      dockerfile: ./docker/redis/Dockerfile-redis
    volumes:
        - ./docker/data/redis:/data

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - db
    ports:
      - "8888:80"


