web:
  build: .
  dockerfile: Dockerfile-nginx
  ports:
    - "8080:80"
  links:
    - php
  volumes:
    - .:/usr/share/nginx/html/attendize
php:
  build: .
  dockerfile: Dockerfile-php
  links:
    - db
    - maildev
    - redis
  volumes:
    - .:/usr/share/nginx/html/attendize
php-worker:
  build: .
  dockerfile: Dockerfile-php
  links:
    - db
    - maildev
    - redis
  volumes:
    - .:/usr/share/nginx/html/attendize
  command: php artisan queue:work --daemon
db:
  image: mysql
  environment:
     MYSQL_USER: attendize
     MYSQL_PASSWORD: attendize
     MYSQL_ROOT_PASSWORD: attendize
     MYSQL_DB: attendize
  ports:
    - "3307:3306"
  volumes:
    - ./docker/mysqldata:/var/lib/mysql
maildev:
  image: djfarrelly/maildev
  ports:
    - "1080:80"
redis:
  image: redis
